spring.application.name=tienda-back



spring.flyway.enabled=true
#Despliegue
#spring.datasource.url=jdbc:mariadb://mariadb-tienda-retoquesexpress:3306/tienda
#Local
spring.datasource.url=jdbc:mariadb://localhost:3306/retoquesexpresdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

