@startuml

class User {
    -Id: int
    -username:String
    -password:String
    -name: String
    -email: String
    -phone: String
}

class Partner {
    -specializations: List<Specialization>
    -level: Level
}
class Client {
    -address: String
}
class Admin {
}

class Service{
    -id:int
    -name:string
    -category:List<CategoryService>
}

class CategoryService{
    -id:int
    -name:string
    -styles:List<Style>
}
class Style{
    -id:int
    -name:string
    -price:double
    -duration: int
}

class Appointment {
    -appointmentId: int
    -client: Client
    -date: Date
    -time: Time
    -location: String
    -apoinmentService: List<ApoinmentService>
    -totalPrice: double
}

class AppoinmentService{
    -partners: List<Partner>
    -services: List<Service>
}

'enum HairCut {
'    TAPER
'    BUZZ_CUT
'    MULLET
'    FRENCH_CROP
'}
'
'enum BeardCut {
'    FULL_BEARD
'    GOATEE
'    MOUSTACHE
'    THREE_DAY_BEARD
'}
'
'enum HairDye {
'    ROOTS
'    HIGHLIGHTS
'    FULL_COLOR
'    BALAYAGE
'}
'
'enum HairStyle {
'    STRAIGHT
'    CURLY
'    WAVY
'    BUN
'}
'
'enum NailPolish {
'    NORMAL
'    SEMI_PERMANENT
'    GEL
'}
'
'enum NailLength {
'    SHORT
'    MEDIUM
'    LONG
'}
'
'enum MakeupType {
'    EVERYDAY
'    NIGHT
'    BRIDE
'    FANTASY
'}


'====Relationships===='
Service -- "1..*" CategoryService
CategoryService -- "1..*" Style

Partner ..|> User
Client ..|> User
Admin ..|> User

Appointment -- AppoinmentService
AppoinmentService -- Service
AppoinmentService -- Partner


@enduml
